language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 0ad51814c9f3104844567edc44b5f55df0679002
  local_dir: build
  on:
    branch: master
